In [101]:
import pandas as pd
import numpy as np

In [102]:
df = pd.read_csv('dataset/WA_Fn-UseC_-HR-Employee-Attrition.csv')

In [103]:
df.shape

(1470, 35)

In [104]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [105]:
df.dtypes

Age                         int64
Attrition                     str
BusinessTravel                str
DailyRate                   int64
Department                    str
DistanceFromHome            int64
Education                   int64
EducationField                str
EmployeeCount               int64
EmployeeNumber              int64
EnvironmentSatisfaction     int64
Gender                        str
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobRole                       str
JobSatisfaction             int64
MaritalStatus                 str
MonthlyIncome               int64
MonthlyRate                 int64
NumCompaniesWorked          int64
Over18                        str
OverTime                      str
PercentSalaryHike           int64
PerformanceRating           int64
RelationshipSatisfaction    int64
StandardHours               int64
StockOptionLevel            int64
TotalWorkingYears           int64
TrainingTimesLastYear       int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

In [106]:
df.head(1)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5

In [107]:
df.describe(include='all')

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470,1470,1470.000000,1470,1470.000000,1470.000000,1470,1470.0,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
unique,NaN,2,3,NaN,3,NaN,NaN,6,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,No,Travel_Rarely,NaN,Research & Development,NaN,NaN,Life Sciences,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1233,1043,NaN,961,NaN,NaN,606,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,36.923810,NaN,NaN,802.485714,NaN,9.192517,2.912925,NaN,1.0,1024.865306,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,NaN,NaN,403.509100,NaN,8.106864,1.024165,NaN,0.0,602.024335,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,NaN,NaN,102.000000,NaN,1.000000,1.000000,NaN,1.0,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,NaN,NaN,465.000000,NaN,2.000000,2.000000,NaN,1.0,491.250000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,NaN,NaN,802.000000,NaN,7.000000,3.000000,NaN,1.0,1020.500000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,NaN,NaN,1157.000000,NaN,14.000000,4.000000,NaN,1.0,1555.750000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,NaN,NaN,1499.000000,NaN,29.000000,5.000000,NaN,1.0,2068.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [108]:
df.duplicated().sum()

np.int64(0)

In [109]:
df.nunique()

Age                           43
Attrition                      2
BusinessTravel                 3
DailyRate                    886
Department                     3
DistanceFromHome              29
Education                      5
EducationField                 6
EmployeeCount                  1
EmployeeNumber              1470
EnvironmentSatisfaction        4
Gender                         2
HourlyRate                    71
JobInvolvement                 4
JobLevel                       5
JobRole                        9
JobSatisfaction                4
MaritalStatus                  3
MonthlyIncome               1349
MonthlyRate                 1427
NumCompaniesWorked            10
Over18                         1
OverTime                       2
PercentSalaryHike             15
PerformanceRating              2
RelationshipSatisfaction       4
StandardHours                  1
StockOptionLevel               4
TotalWorkingYears             40
TrainingTimesLastYear          7
WorkLifeBalance                4
YearsAtCompany                37
YearsInCurrentRole            19
YearsSinceLastPromotion       16
YearsWithCurrManager          18
dtype: int64

In [110]:
cols_remover = [col for col in df.columns if df[col].nunique() == 1]
df = df.drop(columns=cols_remover)
print(f"Colunas com valores unicos removidas {cols_remover}")

Colunas com valores unicos removidas ['EmployeeCount', 'Over18', 'StandardHours']

In [111]:
df.shape

(1470, 32)

In [112]:
colunas_str = df.select_dtypes(include=['str']).columns.tolist()

print(colunas_str)

['Attrition', 'BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'OverTime']

In [113]:
df['Status'] = df['Attrition'].map({
    'Yes': 'Desligado',
    'No': 'Ativo'
})

In [114]:
df['Department'].unique()

<StringArray>
['Sales', 'Research & Development', 'Human Resources']
Length: 3, dtype: str

In [115]:
df['Departamento'] = df['Department'].map({
    'Sales': 'Vendas',
    'Research & Development': 'P&D',
    'Human Resources': 'RH'
})

In [116]:
df['HorasExtras'] = df['OverTime'].map({
    'Yes': 'Sim',
    'No': 'Não'
})

In [117]:
df['nivelCargo'] = df['JobLevel'].map({
    1: 'Jr',
    2: 'Pleno',
    3: 'Senior',
    4: 'Especialista',
    5: 'Diretor',
})

In [118]:
df = df.rename(columns={'nivelCargo': 'NivelCargo'})

In [119]:
df['FaixaSalarial'] = pd.cut(
    df['MonthlyIncome'],
    bins = [0, 3000, 6000, 10000, 20000],
    labels=['Até 3k', '3k-6k', '6k-10k', 'Acima 10k'],
    ordered=True
)

In [120]:
df['FaixaIdade'] = pd.cut(
    df['Age'],
    bins=[17, 25, 35, 45, 100],
    labels=['18–25', '26–35', '36–45', '46+'],
    ordered=True
)

In [121]:
df['FaixaTempoEmpresa'] = pd.cut(
    df['YearsAtCompany'],
    bins=[-1, 2, 5, 10, 30],
    labels=['0-2 anos', '3-5 anos', '6-10 anos', '10+ anos'],
    ordered=True
)

In [122]:
df['CustoTurnover'] = np.where(
    df['Status'] == 'Desligado',
    df['MonthlyIncome'] * 12 * 1.5,
    0
)

In [126]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeNumber',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager', 'Status',
       'Departamento', 'HorasExtras', 'NivelCargo', 'FaixaSalarial',
       'FaixaIdade', 'FaixaTempoEmpresa', 'CustoTurnover'],
      dtype='str')

In [129]:
tunover = df['Status'].value_counts()
tunover

Status
Ativo        1233
Desligado     237
Name: count, dtype: int64

In [133]:
percentual = tunover['Desligado'] / len(df) * 100
print(f"Taxa de turnover: {percentual:.1f}%")

Taxa de turnover: 16.1%

In [137]:
df.groupby('Departamento')['Status'].apply(lambda x: (x == 'Desligado').sum() / len(x) * 100).round(1)

Departamento
P&D       13.8
RH        19.0
Vendas    20.6
Name: Status, dtype: float64

In [142]:
df.groupby('HorasExtras')['Status'].apply(lambda x: (x == 'Desligado').sum() / len(x) * 100).round(1)

HorasExtras
Não    10.4
Sim    30.5
Name: Status, dtype: float64

In [149]:
df.groupby('Status')['MonthlyIncome'].mean().round(0)

Status
Ativo        6833.0
Desligado    4787.0
Name: MonthlyIncome, dtype: float64

In [151]:
df.to_csv('dataset/rh_tratato.csv')

In [152]:
df.to_excel('dataset/rh_tratato.xlsx')

In [155]:
from sqlalchemy import create_engine

df = pd.read_csv('dataset/rh_tratato.csv')

engine = create_engine('postgresql://postgres:admin@localhost:5432/hr_analytics')

df.to_sql('dados_hr', engine, if_exists='replace', index=False)

print("Tabela criada com sucesso!")
print(f"Linhas inseridas: {len(df)}")

Tabela criada com sucesso!
Linhas inseridas: 1470